# Generated by Django 4.2.4 on 2023-09-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('review_date', models.DateField()),
                ('platform_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('review_details', models.TextField()),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
    ]
