# Generated by Django 4.2.4 on 2023-09-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='platform_icon',
        ),
        migrations.AddField(
            model_name='review',
            name='platform_image',
            field=models.ImageField(blank=True, null=True, upload_to='platform_images'),
        ),
    ]
