# Generated by Django 4.2.4 on 2023-09-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_review_platform_icon_review_platform_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='platform_image',
        ),
        migrations.AddField(
            model_name='review',
            name='platform_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
