# Generated by Django 4.2.4 on 2023-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_review_platform_image_review_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='has_features',
            field=models.BooleanField(default=False),
        ),
    ]
