# Generated by Django 4.2.4 on 2023-09-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_review_has_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_images')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('feature_image', models.ImageField(blank=True, null=True, upload_to='portfolio_images')),
                ('feature_portfolio', models.TextField()),
                ('client_name', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('services_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='portfolio_images')),
                ('overview', models.TextField()),
                ('solution', models.TextField()),
                ('multiple_images', models.ManyToManyField(blank=True, to='backend.multipleimage')),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.review')),
            ],
        ),
    ]
