# Generated by Django 4.2.4 on 2023-09-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_multipleimage_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('project_summary', models.TextField()),
                ('budget', models.CharField(max_length=50)),
                ('agree_to_newsletters', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='multiple_images',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='MultipleImage',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
