# Generated by Django 4.2.4 on 2023-09-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_contactsubmission_remove_portfolio_multiple_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
