# Generated by Django 4.2.4 on 2023-09-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_timestamp_contactformsubmission_submission_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='project_summary',
            field=models.TextField(max_length=2000),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=100)),
                ('portfolio_feature_image', models.ImageField(upload_to='portfolio/images/')),
                ('client_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cover_image', models.ImageField(upload_to='portfolio/cover_images/')),
                ('overview', models.TextField()),
                ('image1', models.ImageField(upload_to='portfolio/images/')),
                ('image2', models.ImageField(upload_to='portfolio/images/')),
                ('image3', models.ImageField(upload_to='portfolio/images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.portfoliocategory')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.review')),
            ],
        ),
    ]
