# Generated by Django 4.2.4 on 2023-09-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_blog_blogcategory_blogtag_comment_blog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
