# Generated by Django 4.2.4 on 2023-09-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('pin', models.CharField(max_length=200)),
            ],
        ),
    ]
