# Generated by Django 4.2.4 on 2023-09-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='ServiceLocation',
        ),
    ]
