# Generated by Django 4.2.4 on 2023-09-02 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_comment_blog_delete_blog_delete_blogcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormSubmission',
        ),
    ]
