# Generated by Django 4.2.4 on 2023-09-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_delete_contactformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='partner/images/')),
            ],
        ),
    ]
