# Generated by Django 4.2.4 on 2023-09-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('project_summary', models.TextField(max_length=2000)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
