# Generated by Django 4.2.4 on 2023-09-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='project_summary',
            field=models.TextField(max_length=2000, verbose_name='Project Summary'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submission Date'),
        ),
    ]
