# Generated by Django 4.2.4 on 2023-09-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactformsubmission_budget_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformsubmission',
            options={'verbose_name_plural': 'Contact Form Submissions'},
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='newsletter_subscription',
            field=models.BooleanField(default=False, verbose_name='Newsletter Subscription'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='budget',
            field=models.CharField(choices=[('₹ 100000 and above', '₹ 100000 and above'), ('₹ 3000 - ₹ 10000', '₹ 3000 - ₹ 10000'), ('₹ 10000 - ₹ 400000', '₹ 10000 - ₹ 400000'), ('₹ 40000 - ₹ 100000', '₹ 40000 - ₹ 100000')], max_length=20, verbose_name='Budget'),
        ),
    ]
