# Generated by Django 4.2.4 on 2023-09-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactformsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='budget',
            field=models.CharField(choices=[('NoIdea', "I Don't Have Any Idea"), ('100-200', '₹ 3000 - ₹ 10000'), ('200-500', '₹ 10000 - ₹ 400000'), ('500-1000', '₹ 40000 - ₹ 100000')], max_length=20, verbose_name='Budget'),
        ),
    ]
