# Generated by Django 4.2.4 on 2023-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactformsubmission_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='budget',
            field=models.CharField(choices=[('NoIdea', "I Don't Have Any Idea"), ('3000-10000', '₹ 3000 - ₹ 10000'), ('10000-40000', '₹ 10000 - ₹ 400000'), ('40000-100000', '₹ 40000 - ₹ 100000'), ('100000up', '₹ 100000 And More')], max_length=20, verbose_name='Budget'),
        ),
    ]
